version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dockerappDB
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"   # optional (remove in prod)

  app:
    image: docker-app:latest
    container_name: docker-app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: dockerappDB
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
